Repository AUBGTheHUB/monolith, pull requests merged in 2023-11, with the labels that each got.

#586 #437 Added back button for all admin/dashboard pages
  packages/web/src/AdminRoutesWithBackButton.js
  packages/web/src/App.js
  packages/web/src/components/admin_page/back_button.css
  packages/web/src/components/admin_page/back_button.jsx
  packages/web/src/components/admin_page/s3_page/s3.css
  packages/web/src/components/admin_page/url_shortener/table.jsx
Labels: AWAITING REVIEW

#570 #415 Delete image by url
  packages/py-api/py_api/controllers/uploader_controller.py
  packages/py-api/py_api/routes/uploader_routes.py
Labels: api, AWAITING REVIEW, python

#596 Added check when updating participant
  packages/py-api/py_api/controllers/hackathon_participants_controller.py
Labels: bug, AWAITING REVIEW
