Repository AUBGTheHUB/monolith, pull requests merged in 2024-10, with the labels that each got.

#722 721 update readme file
  Makefile
  README.md
  cli.sh
  docs/github/connected_devContainer.png
  docs/github/gum_interface.png
Labels: documentation, AWAITING REVIEW

#734 Update README.md
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/postCreateCommand.sh
  services/py-api/README.md
Labels: AWAITING REVIEW

#735 Containarize py api
  .github/workflows/pytests.yml
  docker-compose.yml
  services/py-api/.env.sample
  services/py-api/Dockerfile
  services/py-api/shared/README.md
  services/py-api/src/server/certs/README.md
  services/py-api/src/server/certs/localhost.crt
  services/py-api/src/server/certs/localhost.key
  services/py-api/src/server/config/server_config.py
  services/py-api/src/server/logger/logger_factory.py
Labels: devops, AWAITING REVIEW

#742 Hotfix/ Add team_id to the Participant model
  services/py-api/src/database/model/base_model.py
  services/py-api/src/database/model/json_serializer.py
  services/py-api/src/database/model/participant_model.py
  services/py-api/src/database/model/team_model.py
  services/py-api/src/database/repository/base_repository.py
  services/py-api/src/database/repository/participants_repository.py
  services/py-api/src/database/repository/teams_repository.py
  services/py-api/src/database/transaction_manager.py
  services/py-api/src/server/handlers/participants_handlers.py
  services/py-api/src/server/routes/participants_routes.py
  services/py-api/src/server/schemas/response_schemas/schemas.py
  services/py-api/src/service/participants_service.py
Labels: api, AWAITING REVIEW, python

#753 Write tests for db layer
  services/py-api/pyproject.toml
  services/py-api/pytest.ini
  services/py-api/src/database/transaction_manager.py
  services/py-api/src/server/schemas/response_schemas/schemas.py
  services/py-api/tests/conftest.py
  services/py-api/tests/unit_tests/README.md
  services/py-api/tests/unit_tests/test_db_manager.py
  services/py-api/tests/unit_tests/test_trancation_manager.py
Labels: AWAITING REVIEW

#755 Explain how to solve missing SSH keys error in WSL
  README.md
  wsl_ssh_forwarding.sh
Labels: documentation, AWAITING REVIEW, bash

#754 #750 Wrote unit tests and added a guide on how to write integration tests
  services/py-api/tests/conftest.py
  services/py-api/tests/integration_tests/README.md
  services/py-api/tests/integration_tests/conftest.py
  services/py-api/tests/unit_tests/conftest.py
  services/py-api/tests/unit_tests/test_database_layer/__init__.py
  services/py-api/tests/unit_tests/test_database_layer/test_db_manager.py
  services/py-api/tests/unit_tests/test_database_layer/test_model_serialization.py
  services/py-api/tests/unit_tests/test_database_layer/test_participant_repository.py
  services/py-api/tests/unit_tests/test_database_layer/test_team_repository.py
  services/py-api/tests/unit_tests/test_database_layer/test_trancation_manager.py
  services/py-api/tests/unit_tests/test_handlers/__init__.py
  services/py-api/tests/unit_tests/test_handlers/test_participant_handlers.py
  services/py-api/tests/unit_tests/test_handlers/test_utility_handlers.py
  services/py-api/tests/unit_tests/test_service_layer/__init__.py
  services/py-api/tests/unit_tests/test_service_layer/test_participant_service.py
Labels: api, AWAITING REVIEW, python
