Repository AUBGTheHUB/monolith, pull requests merged in 2024-02, with the labels that each got.

#623 Refactored adding of participants workflow
  packages/py-api/poetry.lock
  packages/py-api/py_api/controllers/hackathon/participants_controller.py
  packages/py-api/py_api/controllers/hackathon/verification_controller.py
  packages/py-api/py_api/environment.py
  packages/py-api/py_api/functionality/hackathon/jwt_base.py
  packages/py-api/py_api/functionality/hackathon/participants_base.py
  packages/py-api/py_api/functionality/hackathon/teams_base.py
  packages/py-api/py_api/middleware/auth.py
  packages/py-api/py_api/models/hackathon_teams_models.py
  packages/py-api/py_api/routes/hackathon/participants_routes.py
  packages/py-api/py_api/routes/hackathon/verification_routes.py
  packages/py-api/py_api/services/mailer.py
  packages/py-api/pyproject.toml
Labels: api, AWAITING REVIEW, python

#622 #619 hackaubg landing component background and text
  packages/services/questionnaire/src/app.html
  packages/web/public/index.html
  packages/web/src/App.css
  packages/web/src/components/spa/HackAUBG/HackAUBG.jsx
  packages/web/src/components/spa/HackAUBG/LandingBackground/Background.jsx
  packages/web/src/components/spa/HackAUBG/LandingBackground/background.module.css
  packages/web/src/components/spa/HackAUBG/LandingPage/LandingPage.jsx
  packages/web/src/components/spa/HackAUBG/LandingPage/landing_page.module.css
  packages/web/src/components/spa/HackAUBG/hack_aubg.css
  packages/web/src/components/spa/LandingSection/LandingSection.jsx
  packages/web/src/components/spa/LandingSection/landing_section.module.css
  packages/web/src/components/spa/MainPage.jsx
  packages/web/src/components/spa/Navigation/DesktopNav/NavDesktop.jsx
  packages/web/src/components/spa/Navigation/DesktopNav/desktop_navbar.css
  packages/web/src/components/spa/Navigation/MobileNav/mobile_navbar.css
Labels: frontend, AWAITING REVIEW

#632 #626 Journey Section
  packages/web/public/step-1-blur.svg
  packages/web/public/step-1-figure.svg
  packages/web/public/step-1-icon-mobile.svg
  packages/web/public/step-1-icon.svg
  packages/web/public/step-1-stripe.svg
  packages/web/public/step-2-blur.svg
  packages/web/public/step-2-figure.svg
  packages/web/public/step-2-icon-mobile.svg
  packages/web/public/step-2-icon.svg
  packages/web/public/step-3-blur.svg
  packages/web/public/step-3-figure.svg
  packages/web/public/step-3-icon-mobile.svg
  packages/web/public/step-3-icon.svg
  packages/web/public/step-4-blur.svg
  packages/web/public/step-4-figure.svg
  packages/web/public/step-4-icon-mobile.svg
  packages/web/public/step-4-icon.svg
  packages/web/src/App.css
  packages/web/src/components/spa/HackAUBG/JourneySection/JourneyDesktop/JourneyDesktop.jsx
  packages/web/src/components/spa/HackAUBG/JourneySection/JourneyDesktop/JourneyStep.jsx
  packages/web/src/components/spa/HackAUBG/JourneySection/JourneyDesktop/JourneyStepVisuals.jsx
  packages/web/src/components/spa/HackAUBG/JourneySection/JourneyDesktop/journey_desktop.css
  packages/web/src/components/spa/HackAUBG/JourneySection/JourneyMobile/JourneyMobile.jsx
  packages/web/src/components/spa/HackAUBG/JourneySection/JourneyMobile/JourneyStep.jsx
  packages/web/src/components/spa/HackAUBG/JourneySection/JourneyMobile/journey_mobile.css
  packages/web/src/components/spa/HackAUBG/JourneySection/data.json
  packages/web/src/components/spa/HackAUBG/hack_aubg.css
Labels: AWAITING REVIEW

#638 #635 Adds new fields to the pydantic participant model
  packages/py-api/py_api/functionality/hackathon/participants_base.py
  packages/py-api/py_api/models/hackathon_participants_models.py
Labels: AWAITING REVIEW

#641 Added urls for frontend and some minor optimizations to registration workflow
  packages/py-api/py_api/controllers/hackathon/participants_controller.py
  packages/py-api/py_api/environment.py
  packages/py-api/py_api/functionality/hackathon/jwt_base.py
  packages/py-api/py_api/functionality/hackathon/participants_base.py
Labels: AWAITING REVIEW

#646 Verify Account Pop Up Message
  packages/web/src/App.css
  packages/web/src/App.js
  packages/web/src/Global.js
  packages/web/src/components/spa/HackAUBG/HackAUBG.jsx
  packages/web/src/components/spa/HackAUBG/VerifyAccountPop/VerifyAccount.jsx
  packages/web/src/components/spa/HackAUBG/VerifyAccountPop/verify_account.module.css
  packages/web/src/components/spa/HackAUBG/hack_aubg.css
  packages/web/src/components/spa/Navigation/DesktopNav/NavDesktop.jsx
  packages/web/src/components/spa/Navigation/MobileNav/NavMobile.jsx
Labels: high priority, frontend, AWAITING REVIEW

#658 651-FAQ-text
  packages/web/src/components/spa/HackAUBG/FAQSection/data.json
Labels: AWAITING REVIEW

#647 Refactor exception handling and mongo queires
  packages/py-api/py_api/controllers/hackathon/participants_controller.py
  packages/py-api/py_api/controllers/hackathon/teams_controller.py
  packages/py-api/py_api/controllers/hackathon/verification_controller.py
  packages/py-api/py_api/database/database_transaction_handlers.py
  packages/py-api/py_api/functionality/hackathon/participants_base.py
  packages/py-api/py_api/functionality/hackathon/teams_base.py
Labels: AWAITING REVIEW

#659 629 mentors carousel
  packages/web/package-lock.json
  packages/web/package.json
  packages/web/public/Pacman-left.png
  packages/web/public/Pacman-right.png
  packages/web/public/arrow-left.png
  packages/web/public/arrow-right.png
  packages/web/src/components/spa/HackAUBG/Carousel.jsx
  packages/web/src/components/spa/HackAUBG/JudgesSection/JudgesCard.jsx
  packages/web/src/components/spa/HackAUBG/JudgesSection/JudgesSection.jsx
  packages/web/src/components/spa/HackAUBG/JudgesSection/judges_section.css
  packages/web/src/components/spa/HackAUBG/JudgesSection/judges_section.module.css
  packages/web/src/components/spa/HackAUBG/MentorsSection/MentorsCard.jsx
  packages/web/src/components/spa/HackAUBG/MentorsSection/MentorsSection.jsx
  packages/web/src/components/spa/HackAUBG/MentorsSection/mentors_section.css
  packages/web/src/components/spa/HackAUBG/MentorsSection/mentors_section.module.css
Labels: AWAITING REVIEW
