Repository AUBGTheHUB/monolith, pull requests merged in 2025-01, with the labels that each got.

#830 #828 implement About and Past Events Section
  package-lock.json
  package.json
  services/web/index.html
  services/web/package-lock.json
  services/web/package.json
  services/web/public/fintech.png
  services/web/public/hackathon.png
  services/web/public/sample.png
  services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/css/base.css
  services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/css/embla.css
  services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/js/EmblaCarousel.tsx
  services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/js/EmblaCarouselArrowButtons.tsx
  services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/js/EmblaCarouselDotButton.tsx
  services/web/src/components/ui/button.tsx
  services/web/src/index.css
  services/web/src/website/MainPage/AboutSection/StaticContent/pastEvents.json
  services/web/src/website/MainPage/AboutSection/components/EventTicket.tsx
  services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
  services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
  services/web/src/website/MainPage/MainPage.tsx
  services/web/styles.css
  services/web/tailwind.config.js
Labels: frontend, AWAITING REVIEW, javascript

#825 #824 Write Unit and Integration Tests for Delete Endpoints
  services/py-api/src/server/handlers/hackathon_handlers.py
  services/py-api/src/server/handlers/participants_handlers.py
  services/py-api/tests/integration_tests/conftest.py
  services/py-api/tests/integration_tests/test_participant_routes.py
  services/py-api/tests/integration_tests/test_team_routes.py
  services/py-api/tests/unit_tests/conftest.py
  services/py-api/tests/unit_tests/test_database_layer/test_participant_repository.py
  services/py-api/tests/unit_tests/test_database_layer/test_team_repository.py
  services/py-api/tests/unit_tests/test_handlers/test_hackathon_handlers.py
  services/py-api/tests/unit_tests/test_handlers/test_participant_handlers.py
Labels: api, AWAITING REVIEW, python

#841 #808 verify random participant flow
  services/py-api/src/database/model/participant_model.py
  services/py-api/src/database/repository/participants_repository.py
  services/py-api/src/database/repository/teams_repository.py
  services/py-api/src/server/exception.py
  services/py-api/src/server/handlers/verification_handlers.py
  services/py-api/src/server/routes/routes.py
  services/py-api/src/server/routes/verification_routes.py
  services/py-api/src/server/schemas/jwt_schemas/schemas.py
  services/py-api/src/server/schemas/request_schemas/schemas.py
  services/py-api/src/server/schemas/response_schemas/schemas.py
  services/py-api/src/service/hackathon_service.py
  services/py-api/src/service/participants_registration_service.py
  services/py-api/src/service/participants_verification_service.py
  services/py-api/src/utils.py
  services/py-api/tests/integration_tests/conftest.py
  services/py-api/tests/integration_tests/test_jwt_utility.py
  services/py-api/tests/integration_tests/test_participant_routes.py
  services/py-api/tests/integration_tests/test_verification_routes.py
  services/py-api/tests/unit_tests/conftest.py
  services/py-api/tests/unit_tests/test_database_layer/test_participant_repository.py
  services/py-api/tests/unit_tests/test_database_layer/test_team_repository.py
  services/py-api/tests/unit_tests/test_handlers/test_verification_handlers.py
  services/py-api/tests/unit_tests/test_service_layer/test_hackathon_service.py
  services/py-api/tests/unit_tests/test_service_layer/test_participant_registration_service.py
Labels: api, AWAITING REVIEW

#817 #807 added admin participant verification
  services/py-api/src/database/model/base_model.py
  services/py-api/src/database/model/participant_model.py
  services/py-api/src/database/model/team_model.py
  services/py-api/src/database/repository/participants_repository.py
  services/py-api/src/database/repository/teams_repository.py
  services/py-api/src/database/transaction_manager.py
  services/py-api/src/server/handlers/verification_handlers.py
  services/py-api/src/server/routes/routes.py
  services/py-api/src/service/__init__.py
  services/py-api/src/service/hackathon_service.py
  services/py-api/src/service/participants_verification_service.py
  services/py-api/tests/integration_tests/test_participant_routes.py
  services/py-api/tests/integration_tests/test_team_routes.py
  services/py-api/tests/integration_tests/test_verification_routes.py
  services/py-api/tests/unit_tests/conftest.py
  services/py-api/tests/unit_tests/test_database_layer/test_participant_repository.py
  services/py-api/tests/unit_tests/test_database_layer/test_team_repository.py
  services/py-api/tests/unit_tests/test_handlers/test_verification_handlers.py
  services/py-api/tests/unit_tests/test_service_layer/test_hackathon_service.py
  services/py-api/tests/unit_tests/test_service_layer/test_participants_verification_service.py
Labels: AWAITING REVIEW

#842 Switch db based on env
  services/py-api/src/database/db_manager.py
  services/py-api/tests/unit_tests/conftest.py
  services/py-api/tests/unit_tests/test_handlers/test_utility_handlers.py
  services/py-api/tests/unit_tests/test_service_layer/test_participant_registration_service.py
Labels: high priority, api, AWAITING REVIEW, python

#850 #847 implement fetch all
  services/py-api/src/database/repository/participants_repository.py
  services/py-api/src/database/repository/teams_repository.py
  services/py-api/tests/unit_tests/test_database_layer/test_participant_repository.py
  services/py-api/tests/unit_tests/test_database_layer/test_team_repository.py
Labels: AWAITING REVIEW

#834 #831 Implement HackAUBG Section
  services/web/public/mentor.png
  services/web/public/participate.png
  services/web/public/question-mark.png
  services/web/src/website/MainPage/HackAUBGSection/HackAUBGSection.tsx
  services/web/src/website/MainPage/MainPage.tsx
Labels: frontend, AWAITING REVIEW
