Repository AUBGTheHUB/monolith, pull requests merged in 2025-03, with the labels that each got.

#905 Journey section done
  docker-swarm-stack.yml
  services/web/package-lock.json
  services/web/package.json
  services/web/public/JourneySection/symbol.svg
  services/web/src/index.css
  services/web/src/website/HackathonPage/HackathonPage.tsx
  services/web/src/website/HackathonPage/JourneySection/JourneyModule.tsx
  services/web/src/website/HackathonPage/JourneySection/JourneySection.tsx
  services/web/src/website/HackathonPage/JourneySection/StaticContent/journeyEntries.json
  services/web/src/website/HackathonPage/components/Recap.tsx
Labels: high priority, AWAITING REVIEW

#943 #936 implement sponsors section
  services/web/src/website/HackathonPage/HackathonPage.tsx
  services/web/src/website/HackathonPage/SponsorsSection/HackathonSponsors.tsx
  services/web/src/website/HackathonPage/SponsorsSection/constants.tsx
Labels: high priority, frontend, READY FOR REVIEW, javascript

#949 remove embla carousel from past events section
  services/web/index.html
  services/web/public/HackAUBG5.webp
  services/web/public/HackAUBG6.webp
  services/web/public/fintech.png
  services/web/public/fintech.webp
  services/web/public/hackathon.png
  services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/css/embla.css
  services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/js/EmblaCarousel.tsx
  services/web/src/website/HackathonPage/CarouselComponents/components/JurySection/components/JurySection.tsx
  services/web/src/website/HackathonPage/FAQSection/HackathonFAQ.tsx
  services/web/src/website/HackathonPage/Footer/HackathonFooter.tsx
  services/web/src/website/HackathonPage/GradingSection/GradingSection.tsx
  services/web/src/website/HackathonPage/JourneySection/JourneySection.tsx
  services/web/src/website/HackathonPage/LandingSection/LandingSection.tsx
  services/web/src/website/HackathonPage/MissionSection/MissionSection.tsx
  services/web/src/website/HackathonPage/Navigation/DesktopNav.tsx
  services/web/src/website/HackathonPage/Navigation/MobileNav.tsx
  services/web/src/website/HackathonPage/ScheduleSection/ScheduleSection.tsx
  services/web/src/website/MainPage/AboutSection/StaticContent/pastEvents.json
  services/web/src/website/MainPage/AboutSection/components/EventTicket.tsx
  services/web/src/website/MainPage/AboutSection/components/PastEventSection.tsx
  services/web/src/website/MainPage/Footer/Footer.tsx
Labels: frontend

#952 883 Implement Registration Form
  package-lock.json
  package.json
  services/web/package-lock.json
  services/web/package.json
  services/web/public/RegistrationForm/reg_line.svg
  services/web/public/RegistrationForm/s.png
  services/web/src/App.tsx
  services/web/src/internal_library/DropdownComponent/DropdownComponent.tsx
  services/web/src/internal_library/InputComponent/InputComponent.tsx
  services/web/src/internal_library/RadioComponent/RadioComponent.tsx
  services/web/src/website/RegistrationFormPage/RegistrationForm/RegistrationForm.tsx
  services/web/src/website/RegistrationFormPage/RegistrationForm/constants.ts
  services/web/src/website/RegistrationFormPage/RegistrationForm/schema.ts
  services/web/src/website/RegistrationFormPage/RegistrationFormPage.tsx
Labels: frontend, HackAUBG, AWAITING REVIEW

#955 954 Fix Registration Page Resending Email Issue
  services/web/src/website/RegistrationFormPage/RegistrationForm/RegistrationForm.tsx
Labels: AWAITING REVIEW

#956 947 add animations to both pages
  package-lock.json
  package.json
  services/web/package.json
  services/web/src/website/MainPage/AboutSection/components/IdentitySection.tsx
  services/web/src/website/MainPage/HackAUBGSection/HackAUBGSection.tsx
  services/web/src/website/MainPage/LandingSection/LandingSection.tsx
Labels: high priority, frontend, QA

#960 #948 correct the text in all pages
  services/web/public/hackLanding/title.svg
  services/web/src/website/HackathonPage/AwardsSection/AwardsSection.tsx
  services/web/src/website/HackathonPage/FAQSection/HackathonFAQ.tsx
  services/web/src/website/HackathonPage/JourneySection/StaticContent/journeyEntries.json
  services/web/src/website/HackathonPage/LandingSection/LandingSection.tsx
  services/web/src/website/HackathonPage/MissionSection/MissionSection.tsx
  services/web/src/website/HackathonPage/ScheduleSection/ScheduleSection.tsx
  services/web/src/website/MainPage/HackAUBGSection/HackAUBGSection.tsx
Labels: frontend, READY FOR REVIEW

#968 967 Make Registration Form Wider and Add Missing Options
  services/py-api/src/database/model/participant_model.py
  services/web/src/website/RegistrationFormPage/RegistrationForm/RegistrationForm.tsx
  services/web/src/website/RegistrationFormPage/RegistrationForm/constants.ts
Labels: AWAITING REVIEW

#971 Add Smoothness Animation On The Registration Page
  package-lock.json
  package.json
  services/web/src/website/RegistrationFormPage/RegistrationForm/RegistrationForm.tsx
Labels: frontend, AWAITING REVIEW
