Repository AUBGTheHUB/monolith, pull requests merged in 2025-02, with the labels that each got.

#858 Secure the staging env using HTTP
  docker-swarm-stack.yml
  services/web/nginx.dev.conf
Labels: devops

#852 fixed controls display
  services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/css/embla-team.css
  services/web/src/website/MainPage/MeetTheTeamSection/components/MeetTheTeam.tsx
Labels: AWAITING REVIEW

#890 879 Implement Schedule Section
  services/web/public/n.png
  services/web/public/schedule_bg.png
  services/web/src/website/HackathonPage/HackathonPage.tsx
  services/web/src/website/HackathonPage/ScheduleSection/ScheduleSection.tsx
Labels: high priority, frontend, AWAITING REVIEW

#899 894 Fix Mobile Circuit Board
  services/web/src/website/MainPage/LandingSection/LandingSection.tsx
Labels: AWAITING REVIEW

#900 #835 implement endpoint for sending verification emails ivan rewrite
  services/py-api/src/database/model/participant_model.py
  services/py-api/src/database/repository/participants_repository.py
  services/py-api/src/database/repository/teams_repository.py
  services/py-api/src/database/transaction_manager.py
  services/py-api/src/environment.py
  services/py-api/src/server/config/server_config.py
  services/py-api/src/server/exception.py
  services/py-api/src/server/handlers/verification_handlers.py
  services/py-api/src/server/routes/dependency_factory.py
  services/py-api/src/server/routes/participants_routes.py
  services/py-api/src/server/routes/verification_routes.py
  services/py-api/src/server/schemas/request_schemas/schemas.py
  services/py-api/src/service/__init__.py
  services/py-api/src/service/hackathon_service.py
  services/py-api/src/service/mail_service/email_templates/email-registration-confirmation.html
  services/py-api/src/service/mail_service/email_templates/email-verify-participant.html
  services/py-api/src/service/mail_service/hackathon_mail_service.py
  services/py-api/src/service/mail_service/mail_client.py
  services/py-api/src/service/mail_service/mail_service.py
  services/py-api/src/service/mail_service/resend_service.py
  services/py-api/src/service/mail_service/utils.py
  services/py-api/src/service/participants_registration_service.py
  services/py-api/src/service/participants_verification_service.py
  services/py-api/src/utils.py
  services/py-api/tests/integration_tests/conftest.py
  services/py-api/tests/integration_tests/test_verification_routes.py
  services/py-api/tests/unit_tests/conftest.py
  services/py-api/tests/unit_tests/test_database_layer/test_participant_repository.py
  services/py-api/tests/unit_tests/test_database_layer/test_team_repository.py
  services/py-api/tests/unit_tests/test_database_layer/test_trancation_manager.py
  services/py-api/tests/unit_tests/test_handlers/test_verification_handlers.py
  services/py-api/tests/unit_tests/test_service_layer/test_hackathon_service.py
  services/py-api/tests/unit_tests/test_service_layer/test_participant_registration_service.py
  services/py-api/tests/unit_tests/test_service_layer/test_participants_verification_service.py
Labels: api, AWAITING REVIEW, python

#911 Add images of the team to the website
  services/web/src/website/MainPage/MeetTheTeamSection/StaticContent/hubbers.json
Labels: high priority, AWAITING REVIEW

#906 881 grading criteria
  services/web/src/website/HackathonPage/GradingSection/GradingSection.tsx
  services/web/src/website/HackathonPage/HackathonPage.tsx
Labels: high priority, AWAITING REVIEW

#897 Mentors and Judges section
  package-lock.json
  package.json
  services/py-api/.env.sample
  services/web/package-lock.json
  services/web/package.json
  services/web/public/jury/jury_line_and_dot.svg
  services/web/public/jury/jury_page_break.svg
  services/web/public/jury/jury_title.svg
  services/web/public/mentors/mentors_title.svg
  services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/css/embla-jury.css
  services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/js/EmblaCarousel.tsx
  services/web/src/config.ts
  services/web/src/constants.ts
  services/web/src/website/HackathonPage/CarouselComponents/JudgesAndMentorsOptions.tsx
  services/web/src/website/HackathonPage/CarouselComponents/JuryAndMentorModule.tsx
  services/web/src/website/HackathonPage/CarouselComponents/components/JurySection/StaticContent/jury.json
  services/web/src/website/HackathonPage/CarouselComponents/components/JurySection/components/JurySection.tsx
  services/web/src/website/HackathonPage/CarouselComponents/components/MentorsSection/StaticContent/mentors.json
  services/web/src/website/HackathonPage/CarouselComponents/components/MentorsSection/components/MentorsSection.tsx
  services/web/src/website/HackathonPage/HackathonPage.tsx
  services/web/src/website/HackathonPage/components/Recap.tsx
Labels: high priority, AWAITING REVIEW

#902 878 landing+mission
  services/py-api/src/service/mail_service/email_templates/email-registration-confirmation.html
  services/py-api/src/service/mail_service/email_templates/email-verify-participant.html
  services/web/public/hackLanding/death_star.svg
  services/web/public/hackLanding/space.svg
  services/web/public/hackLanding/title.svg
  services/web/public/hackMission/mission.svg
  services/web/public/hackMission/underline.svg
  services/web/src/website/HackathonPage/HackathonPage.tsx
  services/web/src/website/HackathonPage/LandingSection/LandingSection.tsx
  services/web/src/website/HackathonPage/MissionSection/MissionSection.tsx
  services/web/src/website/HackathonPage/ScheduleSection/ScheduleSection.tsx
  services/web/tailwind.config.js
Labels: high priority, AWAITING REVIEW

#919 Fix jwt
  services/py-api/src/database/model/json_serializer.py
  services/py-api/src/dependency_wiring.py
  services/py-api/src/server/handlers/hackathon/verification_handlers.py
  services/py-api/src/server/routes/routes_dependencies.py
  services/py-api/src/service/hackathon/hackathon_service.py
  services/py-api/src/service/hackathon/participants_registration_service.py
  services/py-api/src/service/jwt_utils/codec.py
  services/py-api/src/service/jwt_utils/schemas.py
Labels: api, AWAITING REVIEW, python
